// All 28 states and 8 union territories of India (alphabetical)
export const ALL_INDIAN_STATES_AND_UTS = [
  "Andaman and Nicobar Islands",
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chandigarh",
  "Chhattisgarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jammu and Kashmir",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Ladakh",
  "Lakshadweep",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Puducherry",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];

// Fallback designation list (DA cadre). The authoritative list is served by
// GET /api/designations; this is only used if that request fails.
export const DESIGNATIONS = [
  "Divisional Accountant",
  "Divisional Accounts Officer Grade-II",
  "Divisional Accounts Officer Grade-I",
  "Senior Divisional Accounts Officer",
  "Assistant Accounts Officer",
  "Accounts Officer",
];
